---
- name: Install core packages
  hosts: local
  remote_user: sean
  roles:
    - core
    - lastpass
  tags:
    - core
    - lastpass

- name: Install development projects
  hosts: local
  remote_user: sean
  roles:
    - ff1
  tags:
    - dev

- name: Install fun stuff
  hosts: local
  remote_user: sean
  roles:
    - entertainment
  tags:
    - fun

