---
# install lastpass 

- name: ensure dependencies are installed
  pacman:
    name: "{{ item }}"
    state: latest
  become: yes
  become_method: sudo
  with_items:
    - base-devel
    - cmake
    - xclip

- name: clone lastpass repo
  git:
    repo: https://github.com/lastpass/lastpass-cli.git
    dest: /home/sean/lastpass-repo
  ignore_errors: true

- name: install lastpass
  shell: cd /home/sean/lastpass-repo && cmake . && make 
  args:
    creates: /home/sean/lastpass-repo/cmake_install.cmake

- name: install lastpass 
  shell: cd /home/sean/lastpass-repo && make install 
  args:
    creates: /usr/local/bin/lpass
  become: yes
  become_method: sudo
